[config]
licfile = {prompt="Want LICENSE.txt?", yesno=true, default=false}
description = {prompt="Description", default="Creates project scaffolding"}
github_user = {prompt="Github username", default="username"}